remote_theme: daattali/beautiful-jekyll

title: 飞出国Ning

author: 飞出国Ning

navbar-links:
  专业服务: "/#services"
  服务优势: "/#aboutus"
  移民职业: "/#clients"
  移民项目: "/#portfolio"
  联系飞出国: "/contact"

title-img: /assets/img/flyabroad-logo-light-s.png

site-css: "/assets/css/flyabroad.css"

keywords: "飞出国Ning，飞出国加拿大移民专家, 优秀的飞出国加拿大雇主担保移民及各国商业类移民咨询顾问。"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "member@flyabroadvisa.com"
  github: flyabroad
  twitter: flyabroad

url-pretty: "f63.flyabroad.me"

footer-img: "/assets/img/footer-bg.png"

google_analytics: "UA-63569270-1"

timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "飞出国 Ning，最专业的杰出人才移民专家，为梦想而坚守的长期主义者。"
      share-img: "/assets/img/flyabroad-logo-light.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

